# Generated by Django 5.1.2 on 2024-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_volumen', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('paginas', models.IntegerField(default=0)),
                ('anio_lanzamiento', models.IntegerField(default=0)),
                ('comprado', models.BooleanField(default=False)),
            ],
        ),
    ]
