# Generated by Django 5.1.2 on 2024-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=40)),
                ('edad', models.IntegerField(default=0)),
                ('raza', models.CharField(max_length=40)),
                ('vivo', models.BooleanField(default=False)),
            ],
        ),
    ]
